port: 7880
keys:
  p7LNKEBaHJiOeGmFen5GQXABglf71snm: 6PErE43LHsDxfBwqGM8xZq4JZuTMxQnm
rtc:
  port_range_start: 50000
  port_range_end: 60000
  tcp_port: 7881
  use_external_ip: true
logging:
  level: debug
