port: 7880
keys:
  p7LNKEBaHJiOeGmFen5GQXABglf71snm: 6PErE43LHsDxfBwqGM8xZq4JZuTMxQnm
rtc:
  port_range_start: 50000
  port_range_end: 60000
  tcp_port: 7881
  use_external_ip: true
logging:
  level: debug
turn:
  enabled: true
  udp_port: 3478
  tls_port: 5349
  domain: turn.worldsamma.org
  cert_file: fullchain.pem
  key_file: privkey.pem
  relay_range_start: 1024
  relay_range_end: 30000
