services:
  livekit:
    build:
      context: .
      dockerfile: Dockerfile.livekit
    ports:
      - "7880:7880"
      - "7881:7881"
    volumes:
      - ./config.yaml:/etc/livekit/config.yaml:ro
    restart: unless-stopped
    environment:
      - LIVEKIT_API_KEY: p7LNKEBaHJiOeGmFen5GQXABglf71s
      - LIVEKIT_API_SECRET: 6PErE43LHsDxfBwqGM8xZq4JZuTMxQ

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    depends_on:
      - livekit
    command: node backend/index.js

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8081:80"
      - "8443:443"
    depends_on:
      - backend
      - livekit
    volumes:
      - ./frontend/build:/usr/share/nginx/html:ro
