services:
  janus:
    build:
      context: .
      dockerfile: Dockerfile.janus
    ports:
      - "8088:8088" # HTTP REST API
      - "8188:8188" # WebSockets API (exposed only internally)
      - "10000-10200:10000-10200/udp" # Media ports for streaming
    environment:
      - JANUS_LOG_LEVEL=4

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    depends_on:
      - janus
    command: node backend/index.js

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
      - "1935:1935"
    depends_on:
      - backend
      - janus
    volumes:
      - ./frontend/build:/usr/share/nginx/html:ro
    environment:
      - REACT_APP_ADMIN_PASSKEY=165432
      - REACT_APP_API_KEY=AIzaSyDroS6O_Co4FGHTourOkHfAIpGEW_xq6XY
