services:
  livekit:
    build:
      context: .
      dockerfile: Dockerfile.livekit
    expose:
      - 7880

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    depends_on:
      - janus
    command: node backend/index.js

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
      - "1935:1935"
    depends_on:
      - backend
      - janus
    volumes:
      - ./frontend/build:/usr/share/nginx/html:ro
