services:
  livekit:
    image: livekit/livekit-server:latest
    container_name: livekit
    ports:
      - "7880:7880"
    environment:
      - LIVEKIT_API_KEY=livekit
      - LIVEKIT_API_SECRET=livekit
    restart: unless-stopped

  # Optional: Custom Backend (Replace LiveKit backend)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    depends_on:
      - livekit
    command: node backend/index.js

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8081:80"
      - "8443:443"
    depends_on:
      - backend
      - livekit
    volumes:
      - ./frontend/build:/usr/share/nginx/html:ro
