services:
  janus:
    build:
      context: .
      dockerfile: Dockerfile.janus
    network_mode: "host"
    ports:
      - "8088:8088" # HTTP REST API
      - "8188:8188" # WebSockets API
      - "40000-65535:40000-65535/udp" # Media ports for streaming
    environment:
      - JANUS_LOG_LEVEL=4

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    depends_on:
      - janus
    command: node backend/index.js

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
      - "1935:1935"
    depends_on:
      - backend
      - janus
    volumes:
      - ./frontend/build:/usr/share/nginx/html:ro
