services:
  livekit:
    build:
      context: .
      dockerfile: Dockerfile.livekit
    ports:
      - "7880:7880"
      - "50000-60000:50000-60000/udp"
      - "7881:7881"
    volumes:
      - ./config.yaml:/etc/livekit/config.yaml:ro
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    depends_on:
      - livekit
    command: node backend/index.js

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - livekit
    volumes:
      - ./frontend/build:/usr/share/nginx/html:ro
